development:
  adapter: postgresql
  encoding: unicode
  database: sinatra_class_dev
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: sinatra_class_test
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: sinatra_class_prod
  pool: 2
  username: your_username
  password: your_password